# -*- coding: utf-8 -*-
"""Practise Pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10AnDNDtehOArIqhYsBQQgeqRm0KmH1L7
"""

import pandas as pd
df = pd.read_csv("salaries_by_college_major.csv")

df.head()

"""# New Section"""

df.shape

df.columns

df.isna()

df.tail()

clean_df = df.dropna()

clean_df.tail()

clean_df['Starting Median Salary']

clean_df['Starting Median Salary'].max()

clean_df['Starting Median Salary'].idxmax()

clean_df['Undergraduate Major'].loc[43]

clean_df['Undergraduate Major'][43]

clean_df.loc[43]

clean_df['Undergraduate Major']

clean_df.loc[43]

clean_df['Undergraduate Major'][clean_df['Mid-Career Median Salary'].idxmax()]

clean_df['Mid-Career 10th Percentile Salary'][clean_df['Mid-Career Median Salary'].idxmax()]

print(clean_df['Mid-Career Median Salary'].max())

print(f"Index for the max mid career salary: {clean_df['Mid-Career Median Salary'].idxmax()}")

clean_df['Undergraduate Major'][clean_df['Mid-Career Median Salary'].idxmin()]

clean_df['Mid-Career 10th Percentile Salary'][clean_df['Mid-Career Median Salary'].idxmin()]

print(clean_df['Starting Median Salary'].min())

clean_df['Undergraduate Major'].loc[clean_df['Mid-Career Median Salary'].idxmin()]

clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

spread_col = clean_df['Mid-Career 90th Percentile Salary'] - clean_df['Mid-Career 10th Percentile Salary']

clean_df.insert(1, 'Spread', spread_col)

clean_df.head()

clean_df['Mid-Career 90th Percentile Salary'].subtract(clean_df['Mid-Career 10th Percentile Salary'])

low_risk = clean_df.sort_values('Spread')

low_risk[['Undergraduate Major', 'Spread']].head()

highest_potensial = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending=False)

highest_potensial[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

highest_spread = clean_df.sort_values('Spread', ascending=False)

highest_spread[['Undergraduate Major', 'Spread']].head()

clean_df.groupby('Group').count()

clean_df.groupby('Group').mean()

pd.options.display.float_format = '{:,.2f}'.format 
clean_df.groupby('Group').mean()











